# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52ab2431e0ddb4046db79d5481690cdc3afdd2242ff7a62b22c2ec06b31d1c5e9d30789514dd2317d32e0190d3b518c517e69c390dc44b0cf2d75567d5f7e332

test:
  secret_key_base: 2759505bc2ff4888cb8a62d7f03eed58ef455c811b435f3e68923d3396c9d34790b9838cadc5aedc53c17171f8915d2709b43e1292e411b366783e4166d4f22c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
